steps:

  - label: "Some random cmds"
    commands:
      - whoami
    agents:
      queue: "ec2_queue"
      
  - label: "Pulling image"
    plugins:
      - docker#v5.10.0:
          image: "alpine"
          always-pull: true
    commands:
      - echo "Hello Alpine"
      - ls -la
    agents:
      queue: "ec2_queue"
      
  - label: ":lock: Snyk Test"
    command: snyk test --severity-threshold=high --fail-on=all --docker alpine:latest
    key: snyk-test
    agents:
      queue: "ec2_queue"
