steps:
  - label: "Pulling image"
    plugins:
      - docker#v5.10.0:
          image: "alpine"
          always-pull: true

  - label: ":lock: Snyk Test"
    command: snyk test --severity-threshold=high --fail-on=all --docker mesosphere/aws-cli
    key: snyk-test
