steps:
  - label: "Pulling image"
    plugins:
      - docker#v5.10.0:
          image: "alpine"
          always-pull: true
    commands:
      - echo "Hello Alpine"
      - ls -la
      
  - label: ":lock: Snyk Test"
    command: snyk test --severity-threshold=high --fail-on=all --docker alpine:latest
    key: snyk-test
